:LOOP
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24
adb shell input keyevent 24

adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25
adb shell input keyevent 25


goto LOOP
